sequenceDiagram
    participant Controller
    participant Service
    participant Manager

    Note over Controller,Manager: Galaxy Backend

    activate Controller
    Controller->>Service: pydantic
    activate Service
    Service->>Manager: pydantic
    activate Manager
    Note right of Manager: Vanilla Python function calls.<br>Use application components<br>to perform "business logic"
    Manager-->>Service: pydantic
    deactivate Manager
    Service-->>Controller: pydantic
    deactivate Service
    deactivate Controller
