classDiagram
    class BaseWebApplication["galaxy.web.framework.base.WebApplication"] {
        handle_request()
    }
    class WebappWebApplication["galaxy.webapps.base.webapp.WebApplication"]
    class GalaxyWebApplication["galaxy.webapps.galaxy.buildapp.GalaxyWebApplication"]
    class DefaultWebTransaction["galaxy.web.framework.base.DefaultWebTransaction"]
    class GalaxyWebTransaction["galaxy.webapps.base.webapp.GalaxyWebTransaction"]
    BaseWebApplication <|-- WebappWebApplication
    WebappWebApplication <|-- GalaxyWebApplication
    BaseWebApplication *-- DefaultWebTransaction
    DefaultWebTransaction <|-- GalaxyWebTransaction
